# Generated by Django 4.2.1 on 2023-07-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePicture',
        ),
    ]
