# Generated by Django 4.2.1 on 2023-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_profile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(default='./images/default_pfp.jpg', upload_to='images'),
        ),
    ]
